# Using https://github.com/18F/uswds-jekyll
theme: uswds-jekyll

# OpenGraph / Twitter metadata
title: plainlanguage.gov
description: Resources to help writers achieve the goal of clear communication from the federal government to the public.

# GA and GitHub data
# google_analytics_ua: UA-99995535-1
repo: https://github.com/GSA/plainlanguage-website

exclude:
- CONTRIBUTING.md
- _config.yml
- .travis.yml
- .gitignore
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- vendor

styles:
  - /assets/css/main.css

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

collections:
  pages:
    output: true
    #permalink: /:path/

kramdown:
  parse_block_html: true
