# Site settings
title: PlainLanguage.gov
description: Resources to help writers achieve the goal of clear communication from the federal government to the public.

# Using https://github.com/18F/uswds-jekyll
theme: uswds-jekyll

# GA and GitHub data
# google_analytics_ua: UA-99995535-1
repo: https://github.com/GSA/plainlanguage.gov

exclude:
- CONTRIBUTING.md
- circle.yml
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md

styles:
  - /assets/css/main.css

defaults:
  - scope:
      path: ""
      type: "guidelines"
    values:
      layout: "docs"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "docs"

collections:
  guidelines:
    output: true
    permalink: /:collection/:path/
  pages:
    output: true
    permalink: /:path/

kramdown:
  parse_block_html: true
